/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Send a password reset link to the user's email.
 * @summary Forgot Password
 */
export const forgotPasswordBody = zod.object({
  "email": zod.string().describe('The user\'s email address.')
})

export const forgotPasswordResponse = zod.object({
  "message": zod.string().optional()
})

/**
 * Reset the user's password using a reset token.
 * @summary Reset Password
 */
export const resetPasswordBody = zod.object({
  "token": zod.string().describe('The password reset token.'),
  "email": zod.string().describe('The user\'s email address.'),
  "password": zod.string().describe('The new password (minimum 8 characters).'),
  "password_confirmation": zod.string().describe('Password confirmation.')
})

export const resetPasswordResponse = zod.object({
  "message": zod.string().optional()
})

