/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { ForgotPassword200, ResetPassword200 } from "../../models";

export const getForgotPasswordResponseMock = (
  overrideResponse: Partial<ForgotPassword200> = {},
): ForgotPassword200 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getResetPasswordResponseMock = (
  overrideResponse: Partial<ResetPassword200> = {},
): ResetPassword200 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getForgotPasswordMockHandler = (
  overrideResponse?:
    | ForgotPassword200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ForgotPassword200> | ForgotPassword200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/forgot-password",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getForgotPasswordResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getResetPasswordMockHandler = (
  overrideResponse?:
    | ResetPassword200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResetPassword200> | ResetPassword200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/reset-password",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getResetPasswordResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getPasswordManagementMock = () => [
  getForgotPasswordMockHandler(),
  getResetPasswordMockHandler(),
];
