/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ConfirmPassword422Errors } from "./confirmPassword422Errors";

export type ConfirmPassword422 = {
  message?: string;
  errors?: ConfirmPassword422Errors;
};
