/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ForgotPassword422Errors } from "./forgotPassword422Errors";

export type ForgotPassword422 = {
  message?: string;
  errors?: ForgotPassword422Errors;
};
