/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Login422Errors } from "./login422Errors";

export type Login422 = {
  message?: string;
  errors?: Login422Errors;
};
