/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type LoginBody = {
  /**
   * The user's email address.
   */
  email: string;
  /**
   * The user's password.
   */
  password: string;
  /**
   * Whether to remember the user's session.
   */
  remember?: boolean;
};
