/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type Logout204 = { [key: string]: unknown } | null;
