/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type RegisterBody = {
  /**
   * The user's full name.
   */
  name: string;
  /**
   * The user's email address.
   */
  email: string;
  /**
   * The user's password (minimum 8 characters).
   */
  password: string;
  /**
   * Password confirmation.
   */
  password_confirmation: string;
};
