/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Register201User } from "./register201User";

export type Register201 = {
  user?: Register201User;
  token?: string;
};
