/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Register422Errors } from "./register422Errors";

export type Register422 = {
  message?: string;
  errors?: Register422Errors;
};
