/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type Register201User = {
  id?: number;
  name?: string;
  email?: string;
  email_verified_at?: string;
  created_at?: string;
  updated_at?: string;
};
