/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type UpdatePasswordBody = {
  /**
   * The user's current password.
   */
  current_password: string;
  /**
   * The new password (minimum 8 characters).
   */
  password: string;
  /**
   * Password confirmation.
   */
  password_confirmation: string;
};
