/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { User200Data } from "./user200Data";

export type User200 = {
  data?: User200Data;
};
