/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type User200Data = {
  id?: string;
  name?: string;
  email?: string;
  email_verified_at?: string;
  avatar?: string;
  created_at?: string;
  updated_at?: string;
};
