/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type VerifyEmailParams = {
  /**
   * Expiration timestamp.
   */
  expires: number;
  /**
   * URL signature.
   */
  signature: string;
};
