/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Initialize CSRF protection by setting the XSRF-TOKEN cookie for SPA authentication.
 * @summary Get CSRF Cookie
 */
export const getCSRFCookieHeader = zod.object({
  "Referer": zod.string().optional()
})

