/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { GetCSRFCookie204 } from "../../models";

export const getGetCSRFCookieResponseMock = (): GetCSRFCookie204 => ({});

export const getGetCSRFCookieMockHandler = (
  overrideResponse?:
    | GetCSRFCookie204
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetCSRFCookie204> | GetCSRFCookie204),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/sanctum/csrf-cookie",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetCSRFCookieResponseMock(),
        ),
        { status: 204, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getCsrfProtectionMock = () => [getGetCSRFCookieMockHandler()];
