/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetCSRFCookie204 } from "../../models";

import { customClient } from "../../mutator/custom-client";
import type { ErrorType } from "../../mutator/custom-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Initialize CSRF protection by setting the XSRF-TOKEN cookie for SPA authentication.
 * @summary Get CSRF Cookie
 */
export const getCSRFCookie = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<GetCSRFCookie204>(
    { url: `/sanctum/csrf-cookie`, method: "GET", signal },
    options,
  );
};

export const getGetCSRFCookieQueryKey = () => {
  return [`/sanctum/csrf-cookie`] as const;
};

export const getGetCSRFCookieQueryOptions = <
  TData = Awaited<ReturnType<typeof getCSRFCookie>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCSRFCookie>>, TError, TData>
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCSRFCookieQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCSRFCookie>>> = ({
    signal,
  }) => getCSRFCookie(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCSRFCookie>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCSRFCookieQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCSRFCookie>>
>;
export type GetCSRFCookieQueryError = ErrorType<unknown>;

export function useGetCSRFCookie<
  TData = Awaited<ReturnType<typeof getCSRFCookie>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCSRFCookie>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCSRFCookie>>,
          TError,
          Awaited<ReturnType<typeof getCSRFCookie>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCSRFCookie<
  TData = Awaited<ReturnType<typeof getCSRFCookie>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCSRFCookie>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCSRFCookie>>,
          TError,
          Awaited<ReturnType<typeof getCSRFCookie>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCSRFCookie<
  TData = Awaited<ReturnType<typeof getCSRFCookie>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCSRFCookie>>, TError, TData>
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get CSRF Cookie
 */

export function useGetCSRFCookie<
  TData = Awaited<ReturnType<typeof getCSRFCookie>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCSRFCookie>>, TError, TData>
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCSRFCookieQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
