/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ConfirmPassword201,
  ConfirmPassword422,
  ConfirmPasswordBody,
  GetPasswordConfirmationStatus200,
} from "../../models";

import { customClient } from "../../mutator/custom-client";
import type { ErrorType, BodyType } from "../../mutator/custom-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Confirm the user's password for sensitive operations.
 * @summary Confirm Password
 */
export const confirmPassword = (
  confirmPasswordBody: BodyType<ConfirmPasswordBody>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<ConfirmPassword201>(
    {
      url: `/user/confirm-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: confirmPasswordBody,
      signal,
    },
    options,
  );
};

export const getConfirmPasswordMutationOptions = <
  TError = ErrorType<ConfirmPassword422>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmPassword>>,
    TError,
    { data: BodyType<ConfirmPasswordBody> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof confirmPassword>>,
  TError,
  { data: BodyType<ConfirmPasswordBody> },
  TContext
> => {
  const mutationKey = ["confirmPassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof confirmPassword>>,
    { data: BodyType<ConfirmPasswordBody> }
  > = (props) => {
    const { data } = props ?? {};

    return confirmPassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConfirmPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmPassword>>
>;
export type ConfirmPasswordMutationBody = BodyType<ConfirmPasswordBody>;
export type ConfirmPasswordMutationError = ErrorType<ConfirmPassword422>;

/**
 * @summary Confirm Password
 */
export const useConfirmPassword = <
  TError = ErrorType<ConfirmPassword422>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof confirmPassword>>,
      TError,
      { data: BodyType<ConfirmPasswordBody> },
      TContext
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof confirmPassword>>,
  TError,
  { data: BodyType<ConfirmPasswordBody> },
  TContext
> => {
  const mutationOptions = getConfirmPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Check if the user's password has been recently confirmed.
 * @summary Get Password Confirmation Status
 */
export const getPasswordConfirmationStatus = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<GetPasswordConfirmationStatus200>(
    { url: `/user/confirmed-password-status`, method: "GET", signal },
    options,
  );
};

export const getGetPasswordConfirmationStatusQueryKey = () => {
  return [`/user/confirmed-password-status`] as const;
};

export const getGetPasswordConfirmationStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPasswordConfirmationStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPasswordConfirmationStatus>>
  > = ({ signal }) => getPasswordConfirmationStatus(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPasswordConfirmationStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPasswordConfirmationStatus>>
>;
export type GetPasswordConfirmationStatusQueryError = ErrorType<unknown>;

export function useGetPasswordConfirmationStatus<
  TData = Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
          TError,
          Awaited<ReturnType<typeof getPasswordConfirmationStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPasswordConfirmationStatus<
  TData = Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
          TError,
          Awaited<ReturnType<typeof getPasswordConfirmationStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPasswordConfirmationStatus<
  TData = Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Password Confirmation Status
 */

export function useGetPasswordConfirmationStatus<
  TData = Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPasswordConfirmationStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPasswordConfirmationStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
