/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  ConfirmPassword201,
  GetPasswordConfirmationStatus200,
} from "../../models";

export const getConfirmPasswordResponseMock = (
  overrideResponse: Partial<ConfirmPassword201> = {},
): ConfirmPassword201 => ({
  confirmed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getGetPasswordConfirmationStatusResponseMock = (
  overrideResponse: Partial<GetPasswordConfirmationStatus200> = {},
): GetPasswordConfirmationStatus200 => ({
  confirmed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  seconds_until_expiration: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getConfirmPasswordMockHandler = (
  overrideResponse?:
    | ConfirmPassword201
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ConfirmPassword201> | ConfirmPassword201),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/user/confirm-password",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getConfirmPasswordResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetPasswordConfirmationStatusMockHandler = (
  overrideResponse?:
    | GetPasswordConfirmationStatus200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetPasswordConfirmationStatus200>
        | GetPasswordConfirmationStatus200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/user/confirmed-password-status",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetPasswordConfirmationStatusResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getPasswordConfirmationMock = () => [
  getConfirmPasswordMockHandler(),
  getGetPasswordConfirmationStatusMockHandler(),
];
