/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Confirm the user's password for sensitive operations.
 * @summary Confirm Password
 */
export const confirmPasswordBody = zod.object({
  "password": zod.string().describe('The user\'s current password.')
})

/**
 * Check if the user's password has been recently confirmed.
 * @summary Get Password Confirmation Status
 */
export const getPasswordConfirmationStatusResponse = zod.object({
  "confirmed": zod.boolean().optional(),
  "seconds_until_expiration": zod.number().optional()
})

