/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Authenticate a user and return a Sanctum token.
 * @summary Login
 */
export const loginBody = zod.object({
  "email": zod.string().describe('The user\'s email address.'),
  "password": zod.string().describe('The user\'s password.'),
  "remember": zod.boolean().optional().describe('Whether to remember the user\'s session.')
})

export const loginResponse = zod.object({

}).nullable()

/**
 * Register a new user account.
 * @summary Register
 */
export const registerBody = zod.object({
  "name": zod.string().describe('The user\'s full name.'),
  "email": zod.string().describe('The user\'s email address.'),
  "password": zod.string().describe('The user\'s password (minimum 8 characters).'),
  "password_confirmation": zod.string().describe('Password confirmation.')
})

