/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { Login200, Logout204, Register201 } from "../../models";

export const getLoginResponseMock = (): Login200 => ({});

export const getLogoutResponseMock = (): Logout204 => ({});

export const getRegisterResponseMock = (
  overrideResponse: Partial<Register201> = {},
): Register201 => ({
  user: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      email_verified_at: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      created_at: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      updated_at: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    },
    undefined,
  ]),
  token: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getLoginMockHandler = (
  overrideResponse?:
    | Login200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Login200> | Login200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/login",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getLogoutMockHandler = (
  overrideResponse?:
    | Logout204
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Logout204> | Logout204),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/logout",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLogoutResponseMock(),
        ),
        { status: 204, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getRegisterMockHandler = (
  overrideResponse?:
    | Register201
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Register201> | Register201),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/register",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getRegisterResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getAuthenticationMock = () => [
  getLoginMockHandler(),
  getLogoutMockHandler(),
  getRegisterMockHandler(),
];
