/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResendVerificationEmail202,
  VerifyEmail204,
  VerifyEmailParams,
} from "../../models";

import { customClient } from "../../mutator/custom-client";
import type { ErrorType } from "../../mutator/custom-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Resend email verification notification.
 * @summary Resend Verification Email
 */
export const resendVerificationEmail = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<ResendVerificationEmail202>(
    { url: `/email/verification-notification`, method: "POST", signal },
    options,
  );
};

export const getResendVerificationEmailMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resendVerificationEmail>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resendVerificationEmail>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["resendVerificationEmail"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resendVerificationEmail>>,
    void
  > = () => {
    return resendVerificationEmail(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResendVerificationEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof resendVerificationEmail>>
>;

export type ResendVerificationEmailMutationError = ErrorType<unknown>;

/**
 * @summary Resend Verification Email
 */
export const useResendVerificationEmail = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resendVerificationEmail>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof resendVerificationEmail>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getResendVerificationEmailMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Verify user email address.
 * @summary Verify Email
 */
export const verifyEmail = (
  id: number,
  hash: string,
  params: VerifyEmailParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<VerifyEmail204>(
    { url: `/email/verify/${id}/${hash}`, method: "GET", params, signal },
    options,
  );
};

export const getVerifyEmailQueryKey = (
  id?: number,
  hash?: string,
  params?: VerifyEmailParams,
) => {
  return [`/email/verify/${id}/${hash}`, ...(params ? [params] : [])] as const;
};

export const getVerifyEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof verifyEmail>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  hash: string,
  params: VerifyEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getVerifyEmailQueryKey(id, hash, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyEmail>>> = ({
    signal,
  }) => verifyEmail(id, hash, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && hash),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof verifyEmail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyEmailQueryResult = NonNullable<
  Awaited<ReturnType<typeof verifyEmail>>
>;
export type VerifyEmailQueryError = ErrorType<unknown>;

export function useVerifyEmail<
  TData = Awaited<ReturnType<typeof verifyEmail>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  hash: string,
  params: VerifyEmailParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyEmail>>,
          TError,
          Awaited<ReturnType<typeof verifyEmail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyEmail<
  TData = Awaited<ReturnType<typeof verifyEmail>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  hash: string,
  params: VerifyEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyEmail>>,
          TError,
          Awaited<ReturnType<typeof verifyEmail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyEmail<
  TData = Awaited<ReturnType<typeof verifyEmail>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  hash: string,
  params: VerifyEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Verify Email
 */

export function useVerifyEmail<
  TData = Awaited<ReturnType<typeof verifyEmail>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  hash: string,
  params: VerifyEmailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getVerifyEmailQueryOptions(id, hash, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
