/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { ResendVerificationEmail202, VerifyEmail204 } from "../../models";

export const getResendVerificationEmailResponseMock = (
  overrideResponse: Partial<ResendVerificationEmail202> = {},
): ResendVerificationEmail202 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getVerifyEmailResponseMock = (): VerifyEmail204 => ({});

export const getResendVerificationEmailMockHandler = (
  overrideResponse?:
    | ResendVerificationEmail202
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResendVerificationEmail202> | ResendVerificationEmail202),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/email/verification-notification",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getResendVerificationEmailResponseMock(),
        ),
        { status: 202, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getVerifyEmailMockHandler = (
  overrideResponse?:
    | VerifyEmail204
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<VerifyEmail204> | VerifyEmail204),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/email/verify/:id/:hash",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getVerifyEmailResponseMock(),
        ),
        { status: 204, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getEmailVerificationMock = () => [
  getResendVerificationEmailMockHandler(),
  getVerifyEmailMockHandler(),
];
