/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Verify user email address.
 * @summary Verify Email
 */
export const verifyEmailQueryParams = zod.object({
  "expires": zod.number().describe('Expiration timestamp.'),
  "signature": zod.string().describe('URL signature.')
})

