/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { UpdatePassword200, UpdateProfile200 } from "../../models";

export const getUpdateProfileResponseMock = (
  overrideResponse: Partial<UpdateProfile200> = {},
): UpdateProfile200 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUpdatePasswordResponseMock = (
  overrideResponse: Partial<UpdatePassword200> = {},
): UpdatePassword200 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUpdateProfileMockHandler = (
  overrideResponse?:
    | UpdateProfile200
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UpdateProfile200> | UpdateProfile200),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/user/profile-information",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateProfileResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getUpdatePasswordMockHandler = (
  overrideResponse?:
    | UpdatePassword200
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UpdatePassword200> | UpdatePassword200),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/user/password",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdatePasswordResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getUserProfileMock = () => [
  getUpdateProfileMockHandler(),
  getUpdatePasswordMockHandler(),
];
