/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Update the authenticated user's profile information.
 * @summary Update Profile
 */
export const updateProfileBody = zod.object({
  "name": zod.string().describe('The user\'s full name.'),
  "email": zod.string().describe('The user\'s email address.')
})

export const updateProfileResponse = zod.object({
  "message": zod.string().optional()
})

/**
 * Update the authenticated user's password.
 * @summary Update Password
 */
export const updatePasswordBody = zod.object({
  "current_password": zod.string().describe('The user\'s current password.'),
  "password": zod.string().describe('The new password (minimum 8 characters).'),
  "password_confirmation": zod.string().describe('Password confirmation.')
})

export const updatePasswordResponse = zod.object({
  "message": zod.string().optional()
})

