/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and return a Sanctum token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out the authenticated user and revoke their tokens.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post avatar
         * @description Upload and set the authenticated user's avatar image.
         */
        post: operations["postAvatar"];
        /**
         * Delete avatar
         * @description Remove the authenticated user's avatar image.
         */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get CSRF Cookie
         * @description Initialize CSRF protection by setting the XSRF-TOKEN cookie for SPA authentication.
         */
        get: operations["getCSRFCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Info
         * @description Display dashboard information including site counts, page counts, and recent activity.
         */
        get: operations["getDashboardInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/{site_id}/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        /**
         * Get site deployment.
         * @description Get the deployment status of the specified site.
         */
        get: operations["getSiteDeployment"];
        /**
         * Update site deployment.
         * @description Update the deployment of the specified site.
         */
        put: operations["updateSiteDeployment"];
        /**
         * Store site deployment.
         * @description Initiate a new deployment for the specified site.
         */
        post: operations["storeSiteDeployment"];
        /**
         * Delete site deployment.
         * @description Delete the deployment of the specified site.
         */
        delete: operations["deleteSiteDeployment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/{site_id}/deployment/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart site deployment.
         * @description Restart the deployment of the specified site.
         */
        post: operations["restartSiteDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/verification-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification Email
         * @description Resend email verification notification.
         */
        post: operations["resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/verify/{id}/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The user ID.
                 * @example 1
                 */
                id: number;
                /**
                 * @description The verification hash.
                 * @example abc123def456
                 */
                hash: string;
            };
            cookie?: never;
        };
        /**
         * Verify Email
         * @description Verify user email address.
         */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/{site_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        /**
         * Get Pages for a Site
         * @description Display all Pages for the given Site.
         */
        get: operations["getPagesForASite"];
        put?: never;
        /**
         * Create Page for Site
         * @description Store a newly created page for a specific site.
         */
        post: operations["createPageForSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/{site_id}/page/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
                /**
                 * @description The ID of the page.
                 * @example 019abd86-72ee-728c-a9c4-0c9bbeb2ac08
                 */
                page_id: string;
            };
            cookie?: never;
        };
        /**
         * Get Page for Site
         * @description Display the specified page for a specific site.
         */
        get: operations["getPageForSite"];
        /**
         * Update Page for Site
         * @description Update the specified page for a specific site.
         */
        put: operations["updatePageForSite"];
        post?: never;
        /**
         * Delete Page for Site
         * @description Remove the specified page from a specific site.
         */
        delete: operations["deletePageForSite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/confirm-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Password
         * @description Confirm the user's password for sensitive operations.
         */
        post: operations["confirmPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/confirmed-password-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Password Confirmation Status
         * @description Check if the user's password has been recently confirmed.
         */
        get: operations["getPasswordConfirmationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Send a password reset link to the user's email.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset the user's password using a reset token.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schemas
         * @description Display all schemas with pagination.
         */
        get: operations["getSchemas"];
        put?: never;
        /**
         * Create Schema
         * @description Store a newly created schema.
         */
        post: operations["createSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/{schema_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the schema.
                 * @example 019abd86-729a-722e-bbd4-e2a34c4fb0b9
                 */
                schema_id: string;
            };
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Display the specified schema.
         */
        get: operations["getSchema"];
        /**
         * Update Schema
         * @description Update the specified schema.
         */
        put: operations["updateSchema"];
        post?: never;
        /**
         * Delete Schema
         * @description Remove the specified schema.
         */
        delete: operations["deleteSchema"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/{schema_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the schema.
                 * @example 019abd86-729a-722e-bbd4-e2a34c4fb0b9
                 */
                schema_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Schema
         * @description Publish the specified schema.
         */
        post: operations["publishSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sites
         * @description Display all sites for the authenticated user.
         */
        get: operations["getSites"];
        put?: never;
        /**
         * Create Site
         * @description Store a newly created site for the authenticated user.
         */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        /**
         * Get Site
         * @description Display the specified site.
         */
        get: operations["getSite"];
        /**
         * Update Site
         * @description Update the specified site.
         */
        put: operations["updateSite"];
        post?: never;
        /**
         * Delete Site
         * @description Remove the specified site.
         */
        delete: operations["deleteSite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile-information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Profile
         * @description Update the authenticated user's profile information.
         */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Password
         * @description Update the authenticated user's password.
         */
        put: operations["updatePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Return the authenticated user's information.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Delete user
         * @description Delete the authenticated user's account and all associated data.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description The user's password.
                     * @example password123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Login failed - invalid credentials. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "These credentials do not match our records."
                             *     ]
                             */
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's full name.
                     * @example John Doe
                     */
                    name: string;
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description The user's password (minimum 8 characters).
                     * @example password123
                     */
                    password: string;
                    /**
                     * @description Password confirmation.
                     * @example password123
                     */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Registration successful. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email has already been taken."
                             *     ]
                             */
                            email?: string[];
                            /**
                             * @example [
                             *       "The password must be at least 8 characters."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    postAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The avatar image file to upload. Accepted formats are jpeg, jpg, png, gif, and webp. Maximum file size is 2MB. Must be a file. Must be an image. Must not be greater than 2048 kilobytes.
                     */
                    avatar: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Avatar uploaded successfully. */
                        message?: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example File does not exist. */
                        message?: string;
                        /** @example ... */
                        error?: string;
                    } | {
                        /** @example File is too big. */
                        message?: string;
                        /** @example ... */
                        error?: string;
                    };
                };
            };
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getCSRFCookie: {
        parameters: {
            query?: never;
            header?: {
                /** @example https://yourapp.com */
                Referer?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF cookie set successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    getDashboardInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: {
                            /** @example 5 */
                            total_sites?: number;
                            /** @example 3 */
                            published_sites?: number;
                            /** @example 2 */
                            draft_sites?: number;
                            /** @example 12 */
                            total_pages?: number;
                            recent_activity?: {
                                /** @example My Blog */
                                name?: string;
                                /** @example 2 hours ago */
                                updated_at?: string;
                            };
                            latest_site?: {
                                /** @example Portfolio */
                                name?: string;
                                /** @example 1 day ago */
                                created_at?: string;
                            };
                        };
                    };
                };
            };
        };
    };
    getSiteDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    updateSiteDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    storeSiteDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    deleteSiteDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    restartSiteDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification link sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                /**
                 * @description The expiration timestamp of the verification link.
                 * @example 1712345678
                 */
                expires: number;
                /**
                 * @description The signature of the verification link.
                 * @example abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
                 */
                signature: string;
            };
            header?: never;
            path: {
                /**
                 * @description The user ID.
                 * @example 1
                 */
                id: number;
                /**
                 * @description The verification hash.
                 * @example abc123def456
                 */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    getPagesForASite: {
        parameters: {
            query?: {
                /**
                 * @description The page number.
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Number of items per page. Defaults to 15.
                 * @example 16
                 */
                per_page?: number;
            };
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       {
                         *         "id": "019ad225-ad27-71e4-b091-995c2a46733a",
                         *         "title": "Et animi quos velit et fugiat.",
                         *         "url": "/accusantium-harum-mollitia-modi-deserunt-aut-ab",
                         *         "created_at": "2025-11-30T00:24:35.000000Z",
                         *         "updated_at": "2025-11-30T00:24:35.000000Z"
                         *       },
                         *       {
                         *         "id": "019ad225-ad31-719f-8c48-06438018ec12",
                         *         "title": "Assumenda consequatur ut et sunt quisquam.",
                         *         "url": "/ut-eaque-alias-ratione-dolores-sed-rem-ea-ut",
                         *         "created_at": "2025-11-30T00:24:35.000000Z",
                         *         "updated_at": "2025-11-30T00:24:35.000000Z"
                         *       }
                         *     ]
                         */
                        data?: {
                            /** @example 019ad225-ad27-71e4-b091-995c2a46733a */
                            id?: string;
                            /** @example Et animi quos velit et fugiat. */
                            title?: string;
                            /** @example /accusantium-harum-mollitia-modi-deserunt-aut-ab */
                            url?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                        }[];
                        links?: {
                            /** @example /?page=1 */
                            first?: string;
                            /** @example /?page=1 */
                            last?: string;
                            /** @example null */
                            prev?: string;
                            /** @example null */
                            next?: string;
                        };
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 1 */
                            from?: number;
                            /** @example 1 */
                            last_page?: number;
                            /**
                             * @example [
                             *       {
                             *         "url": null,
                             *         "label": "&laquo; Previous",
                             *         "page": null,
                             *         "active": false
                             *       },
                             *       {
                             *         "url": "/?page=1",
                             *         "label": "1",
                             *         "page": 1,
                             *         "active": true
                             *       },
                             *       {
                             *         "url": null,
                             *         "label": "Next &raquo;",
                             *         "page": null,
                             *         "active": false
                             *       }
                             *     ]
                             */
                            links?: {
                                /** @example null */
                                url?: string;
                                /** @example &laquo; Previous */
                                label?: string;
                                /** @example null */
                                page?: string;
                                /** @example false */
                                active?: boolean;
                            }[];
                            /** @example / */
                            path?: string;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 2 */
                            to?: number;
                            /** @example 2 */
                            total?: number;
                        };
                    };
                };
            };
        };
    };
    createPageForSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The title of the page . . Must not be greater than 255 characters.
                     * @example My personal homepage
                     */
                    title: string;
                    /**
                     * @description The URL slug for the post . . Must start with one of <code>/</code> Must not be greater than 255 characters.
                     * @example my - first - post
                     */
                    url: string;
                    /**
                     * @description The HTML content of the page base64 encoded and zlib compressed.
                     * @example eJzT0yMAAGTvBe8 =
                     */
                    html?: string | null;
                    /**
                     * @description The content of the schema, base64 encoded and zlib compressed JSON.
                     * @example eJzT0yMAAGTvBe8 =
                     */
                    content?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ad4d-7241-be64-3550afb5f2e7 */
                            id?: string;
                            /** @example Eius et animi quos velit et. */
                            title?: string;
                            /** @example /perspiciatis-quo-omnis-nostrum-aut-adipisci-quidem-nostrum-qui */
                            url?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example 019abd86-72fe-7241-b6e7-36fb25bbb6af */
                            site_id?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                        };
                    };
                };
            };
        };
    };
    getPageForSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
                /**
                 * @description The ID of the page.
                 * @example 019abd86-72ee-728c-a9c4-0c9bbeb2ac08
                 */
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ad3e-738f-94f2-08b67c43a8ee */
                            id?: string;
                            /** @example Quo culpa laudantium accusamus temporibus. */
                            title?: string;
                            /** @example /modi-reiciendis-nisi-qui-expedita-atque-modi-ipsam-qui */
                            url?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example 019abd86-7307-7368-a6ab-133ffdf4fe4d */
                            site_id?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                        };
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Page not found for the specified site. */
                        message?: string;
                    };
                };
            };
        };
    };
    updatePageForSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
                /**
                 * @description The ID of the page.
                 * @example 019abd86-72ee-728c-a9c4-0c9bbeb2ac08
                 */
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The title of the page . . Must not be greater than 255 characters.
                     * @example My personal homepage
                     */
                    title?: string | null;
                    /**
                     * @description The URL slug for the post . . Must start with one of <code>/</code> Must not be greater than 255 characters.
                     * @example my - first - post
                     */
                    url?: string | null;
                    /**
                     * @description The content of the schema, base64 encoded and zlib compressed JSON.
                     * @example eJzT0yMAAGTvBe8 =
                     */
                    content?: string | null;
                    /**
                     * @description The HTML content of the page base64 encoded and zlib compressed.
                     * @example eJzT0yMAAGTvBe8 =
                     */
                    html?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ad5d-7135-838a-b9a9ba4034b5 */
                            id?: string;
                            /** @example Eius et animi quos velit et. */
                            title?: string;
                            /** @example /incidunt-iure-odit-et-et-modi-ipsum */
                            url?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example 019abd86-7327-706c-9ba7-8bfb9b393136 */
                            site_id?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                        };
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Page not found for the specified site. */
                        message?: string;
                    };
                };
            };
        };
    };
    deletePageForSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
                /**
                 * @description The ID of the page.
                 * @example 019abd86-72ee-728c-a9c4-0c9bbeb2ac08
                 */
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    confirmPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's current password.
                     * @example password123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password confirmed successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Password confirmation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The password is incorrect."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    getPasswordConfirmationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password confirmation status retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        confirmed?: boolean;
                        /** @example 10800 */
                        seconds_until_expiration?: number;
                    };
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Password reset link sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email is invalid."
                             *     ]
                             */
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description The new password (minimum 8 characters).
                     * @example newpassword123
                     */
                    password: string;
                    /**
                     * @description Password confirmation.
                     * @example newpassword123
                     */
                    password_confirmation: string;
                    /**
                     * @description The password reset token.
                     * @example reset_token_123
                     */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Password reset successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email is invalid."
                             *     ]
                             */
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    getSchemas: {
        parameters: {
            query?: {
                /**
                 * @description The page number.
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Number of items per page. Defaults to 15. Max 100.
                 * @example 16
                 */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       {
                         *         "id": "019ad225-ac67-70b2-805b-423a1a7e5c01",
                         *         "name": "eius",
                         *         "description": "Quos velit et fugiat sunt nihil accusantium harum.",
                         *         "state": "draft",
                         *         "content": null,
                         *         "created_at": "2025-11-30T00:24:35.000000Z",
                         *         "updated_at": "2025-11-30T00:24:35.000000Z",
                         *         "published_at": null
                         *       },
                         *       {
                         *         "id": "019ad225-ac69-73bb-adc8-3e72baabeeb8",
                         *         "name": "modi",
                         *         "description": null,
                         *         "state": "published",
                         *         "content": "hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n",
                         *         "created_at": "2025-11-30T00:24:35.000000Z",
                         *         "updated_at": "2025-11-30T00:24:35.000000Z",
                         *         "published_at": null
                         *       }
                         *     ]
                         */
                        data?: {
                            /** @example 019ad225-ac67-70b2-805b-423a1a7e5c01 */
                            id?: string;
                            /** @example eius */
                            name?: string;
                            /** @example Quos velit et fugiat sunt nihil accusantium harum. */
                            description?: string;
                            /** @example draft */
                            state?: string;
                            /** @example null */
                            content?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        }[];
                        links?: {
                            /** @example /?page=1 */
                            first?: string;
                            /** @example /?page=1 */
                            last?: string;
                            /** @example null */
                            prev?: string;
                            /** @example null */
                            next?: string;
                        };
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 1 */
                            from?: number;
                            /** @example 1 */
                            last_page?: number;
                            /**
                             * @example [
                             *       {
                             *         "url": null,
                             *         "label": "&laquo; Previous",
                             *         "page": null,
                             *         "active": false
                             *       },
                             *       {
                             *         "url": "/?page=1",
                             *         "label": "1",
                             *         "page": 1,
                             *         "active": true
                             *       },
                             *       {
                             *         "url": null,
                             *         "label": "Next &raquo;",
                             *         "page": null,
                             *         "active": false
                             *       }
                             *     ]
                             */
                            links?: {
                                /** @example null */
                                url?: string;
                                /** @example &laquo; Previous */
                                label?: string;
                                /** @example null */
                                page?: string;
                                /** @example false */
                                active?: boolean;
                            }[];
                            /** @example / */
                            path?: string;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 2 */
                            to?: number;
                            /** @example 2 */
                            total?: number;
                        };
                    };
                };
            };
        };
    };
    createSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The name of the schema. Must not be greater than 20 characters.
                     * @example Portfolio Schema
                     */
                    name: string;
                    /**
                     * @description A brief description of the schema.
                     * @example A webpage schema for a personal portfolio site.
                     */
                    description?: string | null;
                    /**
                     * @description The content of the schema, base64 encoded and lz compressed JSON.
                     * @example eJzT0yMAAGTvBe8=
                     */
                    content?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ac74-71db-8279-4e676a877bc8 */
                            id?: string;
                            /** @example architecto */
                            name?: string;
                            /** @example null */
                            description?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example draft */
                            state?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the schema.
                 * @example 019abd86-729a-722e-bbd4-e2a34c4fb0b9
                 */
                schema_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ac70-71f8-9495-e6298ec25b52 */
                            id?: string;
                            /** @example provident */
                            name?: string;
                            /** @example Omnis nostrum aut adipisci quidem nostrum qui commodi. */
                            description?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example published */
                            state?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    updateSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the schema.
                 * @example 019abd86-729a-722e-bbd4-e2a34c4fb0b9
                 */
                schema_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The name of the schema. Must not be greater than 20 characters.
                     * @example Portfolio Schema
                     */
                    name: string;
                    /**
                     * @description A brief description of the schema.
                     * @example A webpage schema for a personal portfolio site.
                     */
                    description?: string | null;
                    /**
                     * @description The content of the schema, base64 encoded and lz compressed JSON.
                     * @example eJzT0yMAAGTvBe8=
                     */
                    content?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ac7b-72f6-af74-620babc35ff8 */
                            id?: string;
                            /** @example architecto */
                            name?: string;
                            /** @example null */
                            description?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example published */
                            state?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    deleteSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the schema.
                 * @example 019abd86-729a-722e-bbd4-e2a34c4fb0b9
                 */
                schema_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    publishSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the schema.
                 * @example 019abd86-729a-722e-bbd4-e2a34c4fb0b9
                 */
                schema_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ac78-7103-bfe4-c2c6d31f040a */
                            id?: string;
                            /** @example quos */
                            name?: string;
                            /** @example null */
                            description?: string;
                            /** @example hZBNSwNBDIb/isbrHgSpyFyLYC8t1J4sHtImraGzmWFmtnZd9r+brSIWXDwNQ/J+POlguViswHVQ2sjDmzgHf2SaY21/eCQpIU2DFhTlBH0FkqeoR8zgSmq4gphCzIN0g9vDPoVGyYQ3zAw2RCLRPbiJKUly9NiOWFewbXIJtVnZ7psQsYLboc8WooHYQtYwq28f2pdZjht4rcCLHqzr17DrTfdr/h/Vik/lEug77IeoDBsOnuTqPSRP19ZxZ32f5cNc7u5HkM6+lzQRE+tgdT73KN0fRP0n */
                            content?: string;
                            /** @example draft */
                            state?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    getSites: {
        parameters: {
            query?: {
                /**
                 * @description The page number.
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Number of items per page. Defaults to 15.
                 * @example 16
                 */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       {
                         *         "id": "019ad225-ac82-707d-9e46-d9304ebed0d8",
                         *         "name": "Crooks LLC",
                         *         "subdomain": "rempel",
                         *         "description": "Sunt nihil accusantium harum mollitia.",
                         *         "state": "draft",
                         *         "number_of_pages": 1,
                         *         "created_at": "2025-11-30T00:24:35.000000Z",
                         *         "updated_at": "2025-11-30T00:24:35.000000Z",
                         *         "published_at": null
                         *       },
                         *       {
                         *         "id": "019ad225-ac88-7019-a55f-967ebe8fbcbe",
                         *         "name": "Schuster Inc",
                         *         "subdomain": "cormier",
                         *         "description": "Omnis nostrum aut adipisci quidem nostrum qui commodi.",
                         *         "state": "draft",
                         *         "number_of_pages": 1,
                         *         "created_at": "2025-11-30T00:24:35.000000Z",
                         *         "updated_at": "2025-11-30T00:24:35.000000Z",
                         *         "published_at": "2024-12-13 10:30:30"
                         *       }
                         *     ]
                         */
                        data?: {
                            /** @example 019ad225-ac82-707d-9e46-d9304ebed0d8 */
                            id?: string;
                            /** @example Crooks LLC */
                            name?: string;
                            /** @example rempel */
                            subdomain?: string;
                            /** @example Sunt nihil accusantium harum mollitia. */
                            description?: string;
                            /** @example draft */
                            state?: string;
                            /** @example 1 */
                            number_of_pages?: number;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        }[];
                        links?: {
                            /** @example /?page=1 */
                            first?: string;
                            /** @example /?page=1 */
                            last?: string;
                            /** @example null */
                            prev?: string;
                            /** @example null */
                            next?: string;
                        };
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 1 */
                            from?: number;
                            /** @example 1 */
                            last_page?: number;
                            /**
                             * @example [
                             *       {
                             *         "url": null,
                             *         "label": "&laquo; Previous",
                             *         "page": null,
                             *         "active": false
                             *       },
                             *       {
                             *         "url": "/?page=1",
                             *         "label": "1",
                             *         "page": 1,
                             *         "active": true
                             *       },
                             *       {
                             *         "url": null,
                             *         "label": "Next &raquo;",
                             *         "page": null,
                             *         "active": false
                             *       }
                             *     ]
                             */
                            links?: {
                                /** @example null */
                                url?: string;
                                /** @example &laquo; Previous */
                                label?: string;
                                /** @example null */
                                page?: string;
                                /** @example false */
                                active?: boolean;
                            }[];
                            /** @example / */
                            path?: string;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 2 */
                            to?: number;
                            /** @example 2 */
                            total?: number;
                        };
                    };
                };
            };
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The name of the site. Must not be greater than 255 characters.
                     * @example My Personal Site
                     */
                    name: string;
                    /**
                     * @description The subdomain for the site. Must not be greater than 255 characters.
                     * @example mypersonalsite
                     */
                    subdomain: string;
                    /**
                     * @description A brief description of the site.
                     * @example This is my personal website where I share my projects and blog posts.
                     */
                    description?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ad17-71cf-be71-8d196459b631 */
                            id?: string;
                            /** @example Bailey Ltd */
                            name?: string;
                            /** @example okuneva */
                            subdomain?: string;
                            /** @example null */
                            description?: string;
                            /** @example 019abd86-7270-7172-89eb-55a2394e6a7c */
                            user_id?: string;
                            /** @example draft */
                            state?: string;
                            /** @example 1 */
                            number_of_pages?: number;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example 2024-12-30 12:00:24 */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ac8e-7258-8614-5a0920da75c3 */
                            id?: string;
                            /** @example McLaughlin, Leuschke and Bauch */
                            name?: string;
                            /** @example fritsch */
                            subdomain?: string;
                            /** @example null */
                            description?: string;
                            /** @example 019abd86-7285-7344-943f-fc8016f4d184 */
                            user_id?: string;
                            /** @example draft */
                            state?: string;
                            /** @example 2 */
                            number_of_pages?: number;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example 2025-04-18 03:32:04 */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    updateSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The name of the site. Must not be greater than 255 characters.
                     * @example My Personal Site
                     */
                    name: string;
                    /**
                     * @description A brief description of the site.
                     * @example This is my personal website where I share my projects and blog posts.
                     */
                    description?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ad1e-7192-be03-84f203a278d8 */
                            id?: string;
                            /** @example Bailey Ltd */
                            name?: string;
                            /** @example gulgowski */
                            subdomain?: string;
                            /** @example Nihil accusantium harum mollitia modi deserunt. */
                            description?: string;
                            /** @example 019abd86-7285-7344-943f-fc8016f4d184 */
                            user_id?: string;
                            /** @example draft */
                            state?: string;
                            /** @example 1 */
                            number_of_pages?: number;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                            /** @example null */
                            published_at?: string;
                        };
                    };
                };
            };
        };
    };
    deleteSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the site.
                 * @example 019abd86-72ea-7227-8b92-c033c77c3f74
                 */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's full name.
                     * @example John Doe
                     */
                    name: string;
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Profile updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Profile update failed - validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email has already been taken."
                             *     ]
                             */
                            email?: string[];
                            /**
                             * @example [
                             *       "The password must be at least 8 characters."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's current password.
                     * @example oldpassword123
                     */
                    current_password: string;
                    /**
                     * @description The new password (minimum 8 characters).
                     * @example newpassword123
                     */
                    password: string;
                    /**
                     * @description Password confirmation.
                     * @example newpassword123
                     */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Password updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Password update failed - validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The current password is incorrect."
                             *     ]
                             */
                            current_password?: string[];
                            /**
                             * @example [
                             *       "The password must be at least 8 characters."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 019ad225-ac2c-718a-a5e6-4e224466a49c */
                            id?: string;
                            /** @example Twila Gibson */
                            name?: string;
                            /** @example lemke.bryon@example.net */
                            email?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            email_verified_at?: string;
                            /** @example null */
                            avatar?: string;
                            /** @example false */
                            is_admin?: boolean;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            created_at?: string;
                            /** @example 2025-11-30T00:24:35.000000Z */
                            updated_at?: string;
                        };
                    };
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
