/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and return a Sanctum token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out the authenticated user and revoke their tokens.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get CSRF Cookie
         * @description Initialize CSRF protection by setting the XSRF-TOKEN cookie for SPA authentication.
         */
        get: operations["getCSRFCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/verification-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification Email
         * @description Resend email verification notification.
         */
        post: operations["resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/verify/{id}/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The user ID.
                 * @example 1
                 */
                id: number;
                /**
                 * @description The verification hash.
                 * @example abc123def456
                 */
                hash: string;
            };
            cookie?: never;
        };
        /**
         * Verify Email
         * @description Verify user email address.
         */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Return the authenticated user's information.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Delete user
         * @description Delete the authenticated user's account and all associated data.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/confirm-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Password
         * @description Confirm the user's password for sensitive operations.
         */
        post: operations["confirmPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/confirmed-password-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Password Confirmation Status
         * @description Check if the user's password has been recently confirmed.
         */
        get: operations["getPasswordConfirmationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Send a password reset link to the user's email.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset the user's password using a reset token.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile-information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Profile
         * @description Update the authenticated user's profile information.
         */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Password
         * @description Update the authenticated user's password.
         */
        put: operations["updatePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description The user's password.
                     * @example password123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Login failed - invalid credentials. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "These credentials do not match our records."
                             *     ]
                             */
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's full name.
                     * @example John Doe
                     */
                    name: string;
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description The user's password (minimum 8 characters).
                     * @example password123
                     */
                    password: string;
                    /**
                     * @description Password confirmation.
                     * @example password123
                     */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Registration successful. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email has already been taken."
                             *     ]
                             */
                            email?: string[];
                            /**
                             * @example [
                             *       "The password must be at least 8 characters."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    getCSRFCookie: {
        parameters: {
            query?: never;
            header?: {
                /** @example https://yourapp.com */
                Referer?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF cookie set successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification link sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                /**
                 * @description Expiration timestamp.
                 * @example 1640995200
                 */
                expires: number;
                /**
                 * @description URL signature.
                 * @example def456ghi789
                 */
                signature: string;
            };
            header?: never;
            path: {
                /**
                 * @description The user ID.
                 * @example 1
                 */
                id: number;
                /**
                 * @description The verification hash.
                 * @example abc123def456
                 */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example null */
                            id?: string;
                            /** @example Alvera Kshlerin */
                            name?: string;
                            /** @example carroll.lyla@example.com */
                            email?: string;
                            /** @example 2025-10-19T18:37:28.000000Z */
                            email_verified_at?: string;
                            /** @example null */
                            avatar?: string;
                            /** @example null */
                            created_at?: string;
                            /** @example null */
                            updated_at?: string;
                        };
                    };
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    confirmPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's current password.
                     * @example password123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password confirmed successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Password confirmation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The password is incorrect."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    getPasswordConfirmationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password confirmation status retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        confirmed?: boolean;
                        /** @example 10800 */
                        seconds_until_expiration?: number;
                    };
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Password reset link sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email is invalid."
                             *     ]
                             */
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Password reset successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email is invalid."
                             *     ]
                             */
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's full name.
                     * @example John Doe
                     */
                    name: string;
                    /**
                     * @description The user's email address.
                     * @example user@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Profile updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Profile update failed - validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The email has already been taken."
                             *     ]
                             */
                            email?: string[];
                            /**
                             * @example [
                             *       "The password must be at least 8 characters."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The user's current password.
                     * @example oldpassword123
                     */
                    current_password: string;
                    /**
                     * @description The new password (minimum 8 characters).
                     * @example newpassword123
                     */
                    password: string;
                    /**
                     * @description Password confirmation.
                     * @example newpassword123
                     */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Password updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
            /** @description Password update failed - validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The given data is invalid. */
                        message?: string;
                        errors?: {
                            /**
                             * @example [
                             *       "The current password is incorrect."
                             *     ]
                             */
                            current_password?: string[];
                            /**
                             * @example [
                             *       "The password must be at least 8 characters."
                             *     ]
                             */
                            password?: string[];
                        };
                    };
                };
            };
        };
    };
}
