/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWebsitesRouteImport } from './routes/_app/websites'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AppSchemaIndexRouteImport } from './routes/_app/schema/index'
import { Route as AppEditorIndexRouteImport } from './routes/_app/editor/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as authEmailVerifyIdHashRouteImport } from './routes/(auth)/email.verify.$id.$hash'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsitesRoute = AppWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchemaIndexRoute = AppSchemaIndexRouteImport.update({
  id: '/schema/',
  path: '/schema/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEditorIndexRoute = AppEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authEmailVerifyIdHashRoute = authEmailVerifyIdHashRouteImport.update({
  id: '/(auth)/email/verify/$id/$hash',
  path: '/email/verify/$id/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/websites': typeof AppWebsitesRoute
  '/account': typeof AppAccountIndexRoute
  '/editor': typeof AppEditorIndexRoute
  '/schema': typeof AppSchemaIndexRoute
  '/email/verify/$id/$hash': typeof authEmailVerifyIdHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/websites': typeof AppWebsitesRoute
  '/account': typeof AppAccountIndexRoute
  '/editor': typeof AppEditorIndexRoute
  '/schema': typeof AppSchemaIndexRoute
  '/email/verify/$id/$hash': typeof authEmailVerifyIdHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/websites': typeof AppWebsitesRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/editor/': typeof AppEditorIndexRoute
  '/_app/schema/': typeof AppSchemaIndexRoute
  '/(auth)/email/verify/$id/$hash': typeof authEmailVerifyIdHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/websites'
    | '/account'
    | '/editor'
    | '/schema'
    | '/email/verify/$id/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/websites'
    | '/account'
    | '/editor'
    | '/schema'
    | '/email/verify/$id/$hash'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/_app/dashboard'
    | '/_app/websites'
    | '/_app/account/'
    | '/_app/editor/'
    | '/_app/schema/'
    | '/(auth)/email/verify/$id/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authEmailVerifyIdHashRoute: typeof authEmailVerifyIdHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/websites': {
      id: '/_app/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AppWebsitesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/schema/': {
      id: '/_app/schema/'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof AppSchemaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/editor/': {
      id: '/_app/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppEditorIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/email/verify/$id/$hash': {
      id: '/(auth)/email/verify/$id/$hash'
      path: '/email/verify/$id/$hash'
      fullPath: '/email/verify/$id/$hash'
      preLoaderRoute: typeof authEmailVerifyIdHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppWebsitesRoute: typeof AppWebsitesRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppEditorIndexRoute: typeof AppEditorIndexRoute
  AppSchemaIndexRoute: typeof AppSchemaIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppWebsitesRoute: AppWebsitesRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppEditorIndexRoute: AppEditorIndexRoute,
  AppSchemaIndexRoute: AppSchemaIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authEmailVerifyIdHashRoute: authEmailVerifyIdHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
