/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AppWebsitesRouteRouteImport } from './routes/_app/websites/route'
import { Route as AppSchemasRouteRouteImport } from './routes/_app/schemas/route'
import { Route as AppWebsitesIndexRouteImport } from './routes/_app/websites/index'
import { Route as AppSchemasIndexRouteImport } from './routes/_app/schemas/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AppSchemasCreateRouteImport } from './routes/_app/schemas/create'
import { Route as AppSchemasSchemaIdRouteRouteImport } from './routes/_app/schemas/$schemaId/route'
import { Route as AppSchemasSchemaIdIndexRouteImport } from './routes/_app/schemas/$schemaId/index'
import { Route as AppSchemasSchemaIdEditRouteImport } from './routes/_app/schemas/$schemaId/edit'
import { Route as AppSchemasSchemaIdDesignRouteImport } from './routes/_app/schemas/$schemaId/design'
import { Route as authEmailVerifyIdHashRouteImport } from './routes/(auth)/email.verify.$id.$hash'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsitesRouteRoute = AppWebsitesRouteRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchemasRouteRoute = AppSchemasRouteRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWebsitesIndexRoute = AppWebsitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebsitesRouteRoute,
} as any)
const AppSchemasIndexRoute = AppSchemasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSchemasRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchemasCreateRoute = AppSchemasCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppSchemasRouteRoute,
} as any)
const AppSchemasSchemaIdRouteRoute = AppSchemasSchemaIdRouteRouteImport.update({
  id: '/$schemaId',
  path: '/$schemaId',
  getParentRoute: () => AppSchemasRouteRoute,
} as any)
const AppSchemasSchemaIdIndexRoute = AppSchemasSchemaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSchemasSchemaIdRouteRoute,
} as any)
const AppSchemasSchemaIdEditRoute = AppSchemasSchemaIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppSchemasSchemaIdRouteRoute,
} as any)
const AppSchemasSchemaIdDesignRoute =
  AppSchemasSchemaIdDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AppSchemasSchemaIdRouteRoute,
  } as any)
const authEmailVerifyIdHashRoute = authEmailVerifyIdHashRouteImport.update({
  id: '/(auth)/email/verify/$id/$hash',
  path: '/email/verify/$id/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schemas': typeof AppSchemasRouteRouteWithChildren
  '/websites': typeof AppWebsitesRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/schemas/$schemaId': typeof AppSchemasSchemaIdRouteRouteWithChildren
  '/schemas/create': typeof AppSchemasCreateRoute
  '/account': typeof AppAccountIndexRoute
  '/schemas/': typeof AppSchemasIndexRoute
  '/websites/': typeof AppWebsitesIndexRoute
  '/schemas/$schemaId/design': typeof AppSchemasSchemaIdDesignRoute
  '/schemas/$schemaId/edit': typeof AppSchemasSchemaIdEditRoute
  '/schemas/$schemaId/': typeof AppSchemasSchemaIdIndexRoute
  '/email/verify/$id/$hash': typeof authEmailVerifyIdHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/schemas/create': typeof AppSchemasCreateRoute
  '/account': typeof AppAccountIndexRoute
  '/schemas': typeof AppSchemasIndexRoute
  '/websites': typeof AppWebsitesIndexRoute
  '/schemas/$schemaId/design': typeof AppSchemasSchemaIdDesignRoute
  '/schemas/$schemaId/edit': typeof AppSchemasSchemaIdEditRoute
  '/schemas/$schemaId': typeof AppSchemasSchemaIdIndexRoute
  '/email/verify/$id/$hash': typeof authEmailVerifyIdHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/schemas': typeof AppSchemasRouteRouteWithChildren
  '/_app/websites': typeof AppWebsitesRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/schemas/$schemaId': typeof AppSchemasSchemaIdRouteRouteWithChildren
  '/_app/schemas/create': typeof AppSchemasCreateRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/schemas/': typeof AppSchemasIndexRoute
  '/_app/websites/': typeof AppWebsitesIndexRoute
  '/_app/schemas/$schemaId/design': typeof AppSchemasSchemaIdDesignRoute
  '/_app/schemas/$schemaId/edit': typeof AppSchemasSchemaIdEditRoute
  '/_app/schemas/$schemaId/': typeof AppSchemasSchemaIdIndexRoute
  '/(auth)/email/verify/$id/$hash': typeof authEmailVerifyIdHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/schemas'
    | '/websites'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/schemas/$schemaId'
    | '/schemas/create'
    | '/account'
    | '/schemas/'
    | '/websites/'
    | '/schemas/$schemaId/design'
    | '/schemas/$schemaId/edit'
    | '/schemas/$schemaId/'
    | '/email/verify/$id/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/schemas/create'
    | '/account'
    | '/schemas'
    | '/websites'
    | '/schemas/$schemaId/design'
    | '/schemas/$schemaId/edit'
    | '/schemas/$schemaId'
    | '/email/verify/$id/$hash'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/schemas'
    | '/_app/websites'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/_app/dashboard'
    | '/_app/schemas/$schemaId'
    | '/_app/schemas/create'
    | '/_app/account/'
    | '/_app/schemas/'
    | '/_app/websites/'
    | '/_app/schemas/$schemaId/design'
    | '/_app/schemas/$schemaId/edit'
    | '/_app/schemas/$schemaId/'
    | '/(auth)/email/verify/$id/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authEmailVerifyIdHashRoute: typeof authEmailVerifyIdHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/websites': {
      id: '/_app/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AppWebsitesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/schemas': {
      id: '/_app/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof AppSchemasRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/websites/': {
      id: '/_app/websites/'
      path: '/'
      fullPath: '/websites/'
      preLoaderRoute: typeof AppWebsitesIndexRouteImport
      parentRoute: typeof AppWebsitesRouteRoute
    }
    '/_app/schemas/': {
      id: '/_app/schemas/'
      path: '/'
      fullPath: '/schemas/'
      preLoaderRoute: typeof AppSchemasIndexRouteImport
      parentRoute: typeof AppSchemasRouteRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/schemas/create': {
      id: '/_app/schemas/create'
      path: '/create'
      fullPath: '/schemas/create'
      preLoaderRoute: typeof AppSchemasCreateRouteImport
      parentRoute: typeof AppSchemasRouteRoute
    }
    '/_app/schemas/$schemaId': {
      id: '/_app/schemas/$schemaId'
      path: '/$schemaId'
      fullPath: '/schemas/$schemaId'
      preLoaderRoute: typeof AppSchemasSchemaIdRouteRouteImport
      parentRoute: typeof AppSchemasRouteRoute
    }
    '/_app/schemas/$schemaId/': {
      id: '/_app/schemas/$schemaId/'
      path: '/'
      fullPath: '/schemas/$schemaId/'
      preLoaderRoute: typeof AppSchemasSchemaIdIndexRouteImport
      parentRoute: typeof AppSchemasSchemaIdRouteRoute
    }
    '/_app/schemas/$schemaId/edit': {
      id: '/_app/schemas/$schemaId/edit'
      path: '/edit'
      fullPath: '/schemas/$schemaId/edit'
      preLoaderRoute: typeof AppSchemasSchemaIdEditRouteImport
      parentRoute: typeof AppSchemasSchemaIdRouteRoute
    }
    '/_app/schemas/$schemaId/design': {
      id: '/_app/schemas/$schemaId/design'
      path: '/design'
      fullPath: '/schemas/$schemaId/design'
      preLoaderRoute: typeof AppSchemasSchemaIdDesignRouteImport
      parentRoute: typeof AppSchemasSchemaIdRouteRoute
    }
    '/(auth)/email/verify/$id/$hash': {
      id: '/(auth)/email/verify/$id/$hash'
      path: '/email/verify/$id/$hash'
      fullPath: '/email/verify/$id/$hash'
      preLoaderRoute: typeof authEmailVerifyIdHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSchemasSchemaIdRouteRouteChildren {
  AppSchemasSchemaIdDesignRoute: typeof AppSchemasSchemaIdDesignRoute
  AppSchemasSchemaIdEditRoute: typeof AppSchemasSchemaIdEditRoute
  AppSchemasSchemaIdIndexRoute: typeof AppSchemasSchemaIdIndexRoute
}

const AppSchemasSchemaIdRouteRouteChildren: AppSchemasSchemaIdRouteRouteChildren =
  {
    AppSchemasSchemaIdDesignRoute: AppSchemasSchemaIdDesignRoute,
    AppSchemasSchemaIdEditRoute: AppSchemasSchemaIdEditRoute,
    AppSchemasSchemaIdIndexRoute: AppSchemasSchemaIdIndexRoute,
  }

const AppSchemasSchemaIdRouteRouteWithChildren =
  AppSchemasSchemaIdRouteRoute._addFileChildren(
    AppSchemasSchemaIdRouteRouteChildren,
  )

interface AppSchemasRouteRouteChildren {
  AppSchemasSchemaIdRouteRoute: typeof AppSchemasSchemaIdRouteRouteWithChildren
  AppSchemasCreateRoute: typeof AppSchemasCreateRoute
  AppSchemasIndexRoute: typeof AppSchemasIndexRoute
}

const AppSchemasRouteRouteChildren: AppSchemasRouteRouteChildren = {
  AppSchemasSchemaIdRouteRoute: AppSchemasSchemaIdRouteRouteWithChildren,
  AppSchemasCreateRoute: AppSchemasCreateRoute,
  AppSchemasIndexRoute: AppSchemasIndexRoute,
}

const AppSchemasRouteRouteWithChildren = AppSchemasRouteRoute._addFileChildren(
  AppSchemasRouteRouteChildren,
)

interface AppWebsitesRouteRouteChildren {
  AppWebsitesIndexRoute: typeof AppWebsitesIndexRoute
}

const AppWebsitesRouteRouteChildren: AppWebsitesRouteRouteChildren = {
  AppWebsitesIndexRoute: AppWebsitesIndexRoute,
}

const AppWebsitesRouteRouteWithChildren =
  AppWebsitesRouteRoute._addFileChildren(AppWebsitesRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSchemasRouteRoute: typeof AppSchemasRouteRouteWithChildren
  AppWebsitesRouteRoute: typeof AppWebsitesRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSchemasRouteRoute: AppSchemasRouteRouteWithChildren,
  AppWebsitesRouteRoute: AppWebsitesRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authEmailVerifyIdHashRoute: authEmailVerifyIdHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
