/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Laravel API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Get the authenticated user.
 * @summary User
 */
export const userResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "email_verified_at": zod.string().optional(),
  "avatar": zod.string().optional(),
  "created_at": zod.string().optional(),
  "updated_at": zod.string().optional()
}).optional()
})

